---
- name: Upgrade all packages
  apt: upgrade=dist force_apt_get=yes

- name: Install required packages
  become: yes
  apt: name={{ packages }} state=present

# Fail2Ban Config
- name: Upload Fail2Ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    remote_src: no        
  notify: restart fail2ban